<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>pluginsib-userinformation-soffid</artifactId>
    <packaging>jar</packaging>
    <name>PluginsIB - UserInformation - Soffid</name>
    <parent>
        <groupId>org.fundaciobit.pluginsib.userinformation</groupId>
        <version>4.0.0-SNAPSHOT</version>
        <artifactId>pluginsib-userinformation</artifactId>
    </parent>
    <properties>
        <keycloak.version>8.0.1</keycloak.version> <!-- 8.0.1 -->
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.fundaciobit.pluginsib.userinformation</groupId>
            <artifactId>pluginsib-userinformation-api</artifactId>
            <version>4.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <!-- NOU <version>${resteasy-version}</version> -->
            <exclusions>
                <exclusion>
                    <groupId>org.jboss.resteasy</groupId>
                    <artifactId>resteasy-jaxrs-services</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>net.jcip</groupId>
                    <artifactId>jcip-annotations</artifactId>
                </exclusion>
                <!-- Enforcer: evitar conflicte de convergència amb JBoss EAP 7.2 (1.0.0.Final vs 1.0.1.Final-redhat-1) -->
                <exclusion>
                    <groupId>org.jboss.spec.javax.xml.bind</groupId>
                    <artifactId>jboss-jaxb-api_2.3_spec</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-multipart-provider</artifactId>
            <!-- NOU <version>${resteasy-version}</version> -->
            <exclusions>
                <exclusion>
                    <groupId>com.sun.xml.bind</groupId>
                    <artifactId>jaxb-impl</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.mail</groupId>
                    <artifactId>javax.mail</artifactId>
                </exclusion>
                <!-- Enforcer: evitar conflicte de convergència amb JBoss EAP 7.2 (1.0.0.Final vs 1.0.1.Final-redhat-1) -->
                <exclusion>
                    <groupId>org.jboss.spec.javax.xml.bind</groupId>
                    <artifactId>jboss-jaxb-api_2.3_spec</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- JSON processing: jackson -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <!-- NOU <version>${jackson-version}</version> -->
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <!-- NOU <version>${jackson-version}</version> -->
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <!-- NOU ${jackson-databind-version} -->
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jackson2-provider</artifactId>
            <!-- NOU <version>${resteasy-version}</version> -->
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <!-- NOU <version>${jackson-version}</version> -->
        </dependency>


        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>commons-logging-jboss-logging</artifactId>
        </dependency>
        
        <dependency>
            <artifactId>pluginsib-utils-templateengine</artifactId>
            <groupId>org.fundaciobit.pluginsib.utils</groupId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>

        <!--
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-multipart-provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jaxrs</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>commons-logging-jboss-logging</artifactId>
        </dependency>

        <dependency>
            <artifactId>scim2-sdk-common</artifactId>
            <groupId>com.unboundid.product.scim2</groupId>
            <version>3.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-jackson2-provider</artifactId>
            <scope>test</scope>
        </dependency>
        
        -->

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.25</version>
            <scope>test</scope>
        </dependency>

    </dependencies>




    <profiles>
    
        <!-- Profile jboss72: actiu per defecte -->
        <profile>
            <id>jboss72_def</id>
            <activation>
                <property>
                    <name>!jboss</name>
                </property>
            </activation>
            <dependencies>
                <!-- Dependències específiques per a JBoss 7.2 -->
                <dependency>
                    <groupId>com.sun.mail</groupId>
                    <artifactId>javax.mail</artifactId>
                    <type>jar</type>
                </dependency>
                <dependency>
                    <artifactId>scim2-sdk-common</artifactId>
                    <groupId>com.unboundid.product.scim2</groupId>
                    <version>3.0.0</version>
                </dependency>
            </dependencies>
        </profile>
    
    
        <!-- Profile jboss72: actiu per propietat -->
        <profile>
            <id>jboss72_explicit</id>
            <activation>
                <property>
                    <name>jboss</name>
                    <value>7.2</value>
                </property>
            </activation>
            <dependencies>
                <!-- Dependències específiques per a JBoss 7.2 -->
                <dependency>
                    <groupId>com.sun.mail</groupId>
                    <artifactId>javax.mail</artifactId>
                    <type>jar</type>
                </dependency>
                <dependency>
                    <artifactId>scim2-sdk-common</artifactId>
                    <groupId>com.unboundid.product.scim2</groupId>
                    <version>3.0.0</version>
                </dependency>
            </dependencies>
        </profile>

        <!-- Profile jboss74 actiu per propietat-->
        <profile>
            <id>jboss74_explicit</id>
            <activation>
                <property>
                    <name>jboss</name>
                    <value>7.4</value>
                </property>
            </activation>
            <dependencies>
                <!-- Dependències específiques per a JBoss 7.4 -->
                <dependency>
                    <groupId>com.sun.mail</groupId>
                    <artifactId>jakarta.mail</artifactId>
                </dependency>
                <dependency>
                    <artifactId>scim2-sdk-common</artifactId>
                    <groupId>com.unboundid.product.scim2</groupId>
                    <version>3.0.0</version>
                    <exclusions>
                        <exclusion>
                            <groupId>jakarta.xml.bind</groupId>
                            <artifactId>jakarta.xml.bind-api</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                
                
                <dependency>
                    <groupId>jakarta.xml.bind</groupId>
                    <artifactId>jakarta.xml.bind-api</artifactId>
                    <version>2.3.2</version>
                    <exclusions>
                        <exclusion>
                            <groupId>jakarta.activation</groupId>
                            <artifactId>jakarta.activation-api</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
                
                
                <dependency>
                    <groupId>jakarta.activation</groupId>
                    <artifactId>jakarta.activation-api</artifactId>
                    <version>1.2.2.redhat-00001</version>
                </dependency>
               
                <!--
                <version>2.0.1.Final-redhat-00001</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <groupId>org.jboss.spec.javax.xml.bind</groupId>
    <artifactId>jboss-jaxb-api_2.3_spec</artifactId>
                 -->
                
                
                
                
                
            </dependencies>
        </profile>

    </profiles>
</project>
